#4 =========================================================
# File Name   : ci-cd-kubernetes-deployment.yaml
# Purpose     : End-to-end CI/CD pipeline for Kubernetes deployment
# Description : Includes code quality checks, container security,
#               Docker image build, and Kubernetes deployment
# =========================================================

pipeline {
    agent any

    tools {
        jdk 'jdk24'
        nodejs 'node24'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/githubWithGHANA/devsecops-netflix.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh '''
                    $SCANNER_HOME/bin/sonar-scanner \
                    -Dsonar.projectName=netflix \
                    -Dsonar.projectKey=netflix
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Trivy Filesystem Scan') {
            steps {
                sh 'trivy fs . > trivyfs.txt'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker', toolName: 'docker') {
                        sh '''
                        docker build --build-arg TMDB_V3_API_KEY=xxxxx -t netflix .
                        docker tag netflix ghansyamaws/netflix:latest
                        docker push ghansyamaws/netflix:latest
                        '''
                    }
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image ghansyamaws/netflix:latest > trivyimage.txt'
            }
        }

        stage('Deploy to Container') {
            steps {
                sh 'docker run -d --name netflix -p 3001:80 ghansyamaws/netflix:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    dir('Kubernetes') {
                        withKubeConfig(credentialsId: 'k8s') {
                            sh '''
                            kubectl apply -f deployment.yml
                            kubectl apply -f service.yml
                            '''
                        }
                    }
                }
            }
        }
    }
}
